//
// PlayerSettingsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PlayerSettingsAPI {

    /**
     Get channel player settings
     
     - parameter channelHandle: (path) The video channel handle 
     - parameter raw: (query) Return raw settings without applying instance defaults (optional, default to false)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PlayerChannelSettings
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getChannelPlayerSettings(channelHandle: String, raw: Bool? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PlayerChannelSettings {
        return try await getChannelPlayerSettingsWithRequestBuilder(channelHandle: channelHandle, raw: raw, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get channel player settings
     - GET /api/v1/player-settings/video-channels/{channelHandle}
     - Get player settings for a video channel.
     - parameter channelHandle: (path) The video channel handle 
     - parameter raw: (query) Return raw settings without applying instance defaults (optional, default to false)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PlayerChannelSettings> 
     */
    open class func getChannelPlayerSettingsWithRequestBuilder(channelHandle: String, raw: Bool? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<PlayerChannelSettings> {
        var localVariablePath = "/api/v1/player-settings/video-channels/{channelHandle}"
        let channelHandlePreEscape = "\(APIHelper.mapValueToPathItem(channelHandle))"
        let channelHandlePostEscape = channelHandlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{channelHandle}", with: channelHandlePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "raw": (wrappedValue: raw?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlayerChannelSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get video player settings
     
     - parameter id: (path) The object id, uuid or short uuid 
     - parameter raw: (query) Return raw settings without merging channel defaults (optional, default to false)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PlayerVideoSettings
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getVideoPlayerSettings(id: ApiV1VideosOwnershipIdAcceptPostIdParameter, raw: Bool? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PlayerVideoSettings {
        return try await getVideoPlayerSettingsWithRequestBuilder(id: id, raw: raw, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get video player settings
     - GET /api/v1/player-settings/videos/{id}
     - Get player settings for a specific video. Returns video-specific settings merged with channel player settings.
     - parameter id: (path) The object id, uuid or short uuid 
     - parameter raw: (query) Return raw settings without merging channel defaults (optional, default to false)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PlayerVideoSettings> 
     */
    open class func getVideoPlayerSettingsWithRequestBuilder(id: ApiV1VideosOwnershipIdAcceptPostIdParameter, raw: Bool? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<PlayerVideoSettings> {
        var localVariablePath = "/api/v1/player-settings/videos/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "raw": (wrappedValue: raw?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlayerVideoSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Update channel player settings
     
     - parameter channelHandle: (path) The video channel handle 
     - parameter playerChannelSettingsUpdate: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PlayerChannelSettings
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateChannelPlayerSettings(channelHandle: String, playerChannelSettingsUpdate: PlayerChannelSettingsUpdate? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PlayerChannelSettings {
        return try await updateChannelPlayerSettingsWithRequestBuilder(channelHandle: channelHandle, playerChannelSettingsUpdate: playerChannelSettingsUpdate, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update channel player settings
     - PUT /api/v1/player-settings/video-channels/{channelHandle}
     - Update default player settings for a video channel.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter channelHandle: (path) The video channel handle 
     - parameter playerChannelSettingsUpdate: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PlayerChannelSettings> 
     */
    open class func updateChannelPlayerSettingsWithRequestBuilder(channelHandle: String, playerChannelSettingsUpdate: PlayerChannelSettingsUpdate? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<PlayerChannelSettings> {
        var localVariablePath = "/api/v1/player-settings/video-channels/{channelHandle}"
        let channelHandlePreEscape = "\(APIHelper.mapValueToPathItem(channelHandle))"
        let channelHandlePostEscape = channelHandlePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{channelHandle}", with: channelHandlePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: playerChannelSettingsUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlayerChannelSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update video player settings
     
     - parameter id: (path) The object id, uuid or short uuid 
     - parameter playerVideoSettingsUpdate: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PlayerVideoSettings
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateVideoPlayerSettings(id: ApiV1VideosOwnershipIdAcceptPostIdParameter, playerVideoSettingsUpdate: PlayerVideoSettingsUpdate? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PlayerVideoSettings {
        return try await updateVideoPlayerSettingsWithRequestBuilder(id: id, playerVideoSettingsUpdate: playerVideoSettingsUpdate, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update video player settings
     - PUT /api/v1/player-settings/videos/{id}
     - Update player settings for a specific video
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter id: (path) The object id, uuid or short uuid 
     - parameter playerVideoSettingsUpdate: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PlayerVideoSettings> 
     */
    open class func updateVideoPlayerSettingsWithRequestBuilder(id: ApiV1VideosOwnershipIdAcceptPostIdParameter, playerVideoSettingsUpdate: PlayerVideoSettingsUpdate? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<PlayerVideoSettings> {
        var localVariablePath = "/api/v1/player-settings/videos/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: playerVideoSettingsUpdate, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PlayerVideoSettings>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
