//
// SessionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SessionAPI {

    /**
     List token sessions
     
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiV1UsersIdTokenSessionsGet200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1UsersIdTokenSessionsGet(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ApiV1UsersIdTokenSessionsGet200Response {
        return try await apiV1UsersIdTokenSessionsGetWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List token sessions
     - GET /api/v1/users/{id}/token-sessions
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiV1UsersIdTokenSessionsGet200Response> 
     */
    open class func apiV1UsersIdTokenSessionsGetWithRequestBuilder(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ApiV1UsersIdTokenSessionsGet200Response> {
        var localVariablePath = "/api/v1/users/{id}/token-sessions"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiV1UsersIdTokenSessionsGet200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List token sessions
     
     - parameter id: (path) Entity id 
     - parameter tokenSessionId: (path) Token session Id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1UsersIdTokenSessionsTokenSessionIdRevokeGet(id: Int, tokenSessionId: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1UsersIdTokenSessionsTokenSessionIdRevokeGetWithRequestBuilder(id: id, tokenSessionId: tokenSessionId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List token sessions
     - GET /api/v1/users/{id}/token-sessions/{tokenSessionId}/revoke
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter id: (path) Entity id 
     - parameter tokenSessionId: (path) Token session Id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1UsersIdTokenSessionsTokenSessionIdRevokeGetWithRequestBuilder(id: Int, tokenSessionId: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/users/{id}/token-sessions/{tokenSessionId}/revoke"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let tokenSessionIdPreEscape = "\(APIHelper.mapValueToPathItem(tokenSessionId))"
        let tokenSessionIdPostEscape = tokenSessionIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{tokenSessionId}", with: tokenSessionIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Login prerequisite
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: OAuthClient
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOAuthClient(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> OAuthClient {
        return try await getOAuthClientWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Login prerequisite
     - GET /api/v1/oauth-clients/local
     - You need to retrieve a client id and secret before [logging in](#operation/getOAuthToken).
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<OAuthClient> 
     */
    open class func getOAuthClientWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<OAuthClient> {
        let localVariablePath = "/api/v1/oauth-clients/local"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<OAuthClient>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter grantType
     */
    public enum GrantType_getOAuthToken: String, Sendable, CaseIterable {
        case refreshToken = "refresh_token"
    }

    /**
     Login
     
     - parameter xPeertubeOtp: (header) If the user enabled two factor authentication, you need to provide the OTP code in this header (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter grantType: (form)  (optional)
     - parameter username: (form) immutable name of the user, used to find or mention its actor (optional)
     - parameter password: (form)  (optional)
     - parameter externalAuthToken: (form) If you want to authenticate using an external authentication token you got from an auth plugin (like &#x60;peertube-plugin-auth-openid-connect&#x60; for example) instead of a password or a refresh token, provide it here. (optional)
     - parameter refreshToken: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetOAuthToken200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOAuthToken(xPeertubeOtp: String? = nil, clientId: String? = nil, clientSecret: String? = nil, grantType: GrantType_getOAuthToken? = nil, username: String? = nil, password: String? = nil, externalAuthToken: String? = nil, refreshToken: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetOAuthToken200Response {
        return try await getOAuthTokenWithRequestBuilder(xPeertubeOtp: xPeertubeOtp, clientId: clientId, clientSecret: clientSecret, grantType: grantType, username: username, password: password, externalAuthToken: externalAuthToken, refreshToken: refreshToken, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Login
     - POST /api/v1/users/token
     - With your [client id and secret](#operation/getOAuthClient), you can retrieve an access and refresh tokens.
     - parameter xPeertubeOtp: (header) If the user enabled two factor authentication, you need to provide the OTP code in this header (optional)
     - parameter clientId: (form)  (optional)
     - parameter clientSecret: (form)  (optional)
     - parameter grantType: (form)  (optional)
     - parameter username: (form) immutable name of the user, used to find or mention its actor (optional)
     - parameter password: (form)  (optional)
     - parameter externalAuthToken: (form) If you want to authenticate using an external authentication token you got from an auth plugin (like &#x60;peertube-plugin-auth-openid-connect&#x60; for example) instead of a password or a refresh token, provide it here. (optional)
     - parameter refreshToken: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetOAuthToken200Response> 
     */
    open class func getOAuthTokenWithRequestBuilder(xPeertubeOtp: String? = nil, clientId: String? = nil, clientSecret: String? = nil, grantType: GrantType_getOAuthToken? = nil, username: String? = nil, password: String? = nil, externalAuthToken: String? = nil, refreshToken: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<GetOAuthToken200Response> {
        let localVariablePath = "/api/v1/users/token"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "client_id": clientId?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "client_secret": clientSecret?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "grant_type": grantType?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "username": username?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "password": password?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "externalAuthToken": externalAuthToken?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "refresh_token": refreshToken?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/x-www-form-urlencoded",
            "x-peertube-otp": xPeertubeOtp?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOAuthToken200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Logout
     
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func revokeOAuthToken(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await revokeOAuthTokenWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Logout
     - POST /api/v1/users/revoke-token
     - Revokes your access token and its associated refresh token, destroying your current session.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func revokeOAuthTokenWithRequestBuilder(apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/api/v1/users/revoke-token"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
