//
// VideoImportsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class VideoImportsAPI {

    /**
     Cancel video import
     
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1VideosImportsIdCancelPost(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1VideosImportsIdCancelPostWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Cancel video import
     - POST /api/v1/videos/imports/{id}/cancel
     - Cancel a pending video import
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1VideosImportsIdCancelPostWithRequestBuilder(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/videos/imports/{id}/cancel"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete video import
     
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1VideosImportsIdDelete(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1VideosImportsIdDeleteWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete video import
     - DELETE /api/v1/videos/imports/{id}
     - Delete ended video import
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1VideosImportsIdDeleteWithRequestBuilder(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/videos/imports/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Retry video import
     
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1VideosImportsIdRetryPost(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await apiV1VideosImportsIdRetryPostWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Retry video import
     - POST /api/v1/videos/imports/{id}/retry
     - **PeerTube >= 8.0** Retry a pending video import
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter id: (path) Entity id 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func apiV1VideosImportsIdRetryPostWithRequestBuilder(id: Int, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/videos/imports/{id}/retry"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Import a video
     
     - parameter name: (form) Video name 
     - parameter channelId: (form) Channel id that will contain this video 
     - parameter targetUrl: (form) remote URL where to find the import&#39;s source video (optional)
     - parameter magnetUri: (form) magnet URI allowing to resolve the import&#39;s source video (optional)
     - parameter torrentfile: (form) Torrent file containing only the video file (optional)
     - parameter privacy: (form)  (optional)
     - parameter category: (form) category id of the video (see [/videos/categories](#operation/getCategories)) (optional)
     - parameter licence: (form) licence id of the video (see [/videos/licences](#operation/getLicences)) (optional)
     - parameter language: (form) language id of the video (see [/videos/languages](#operation/getLanguages)) (optional)
     - parameter description: (form) Video description (optional)
     - parameter waitTranscoding: (form) Whether or not we wait transcoding before publish the video (optional)
     - parameter generateTranscription: (form) **PeerTube &gt;&#x3D; 6.2** If enabled by the admin, automatically generate a subtitle of the video (optional)
     - parameter support: (form) A text tell the audience how to support the video creator (optional)
     - parameter nsfw: (form) Whether or not this video contains sensitive content (optional)
     - parameter nsfwSummary: (form) More information about the sensitive content of the video (optional)
     - parameter nsfwFlags: (form)  (optional)
     - parameter tags: (form) Video tags (maximum 5 tags each between 2 and 30 characters) (optional)
     - parameter commentsPolicy: (form)  (optional)
     - parameter downloadEnabled: (form) Enable or disable downloading for this video (optional)
     - parameter originallyPublishedAt: (form) Date when the content was originally published (optional)
     - parameter scheduleUpdate: (form)  (optional)
     - parameter thumbnailfile: (form) Video thumbnail file (optional)
     - parameter previewfile: (form) Video preview file (optional)
     - parameter videoPasswords: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: VideoUploadResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func importVideo(name: String, channelId: Int, targetUrl: String? = nil, magnetUri: String? = nil, torrentfile: URL? = nil, privacy: VideoPrivacySet? = nil, category: Int? = nil, licence: Int? = nil, language: String? = nil, description: String? = nil, waitTranscoding: Bool? = nil, generateTranscription: Bool? = nil, support: String? = nil, nsfw: Bool? = nil, nsfwSummary: JSONValue? = nil, nsfwFlags: NSFWFlag? = nil, tags: Set<String>? = nil, commentsPolicy: VideoCommentsPolicySet? = nil, downloadEnabled: Bool? = nil, originallyPublishedAt: Date? = nil, scheduleUpdate: VideoScheduledUpdate? = nil, thumbnailfile: URL? = nil, previewfile: URL? = nil, videoPasswords: Set<String>? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> VideoUploadResponse {
        return try await importVideoWithRequestBuilder(name: name, channelId: channelId, targetUrl: targetUrl, magnetUri: magnetUri, torrentfile: torrentfile, privacy: privacy, category: category, licence: licence, language: language, description: description, waitTranscoding: waitTranscoding, generateTranscription: generateTranscription, support: support, nsfw: nsfw, nsfwSummary: nsfwSummary, nsfwFlags: nsfwFlags, tags: tags, commentsPolicy: commentsPolicy, downloadEnabled: downloadEnabled, originallyPublishedAt: originallyPublishedAt, scheduleUpdate: scheduleUpdate, thumbnailfile: thumbnailfile, previewfile: previewfile, videoPasswords: videoPasswords, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Import a video
     - POST /api/v1/videos/imports
     - Import a torrent or magnetURI or HTTP resource (if enabled by the instance administrator)
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter name: (form) Video name 
     - parameter channelId: (form) Channel id that will contain this video 
     - parameter targetUrl: (form) remote URL where to find the import&#39;s source video (optional)
     - parameter magnetUri: (form) magnet URI allowing to resolve the import&#39;s source video (optional)
     - parameter torrentfile: (form) Torrent file containing only the video file (optional)
     - parameter privacy: (form)  (optional)
     - parameter category: (form) category id of the video (see [/videos/categories](#operation/getCategories)) (optional)
     - parameter licence: (form) licence id of the video (see [/videos/licences](#operation/getLicences)) (optional)
     - parameter language: (form) language id of the video (see [/videos/languages](#operation/getLanguages)) (optional)
     - parameter description: (form) Video description (optional)
     - parameter waitTranscoding: (form) Whether or not we wait transcoding before publish the video (optional)
     - parameter generateTranscription: (form) **PeerTube &gt;&#x3D; 6.2** If enabled by the admin, automatically generate a subtitle of the video (optional)
     - parameter support: (form) A text tell the audience how to support the video creator (optional)
     - parameter nsfw: (form) Whether or not this video contains sensitive content (optional)
     - parameter nsfwSummary: (form) More information about the sensitive content of the video (optional)
     - parameter nsfwFlags: (form)  (optional)
     - parameter tags: (form) Video tags (maximum 5 tags each between 2 and 30 characters) (optional)
     - parameter commentsPolicy: (form)  (optional)
     - parameter downloadEnabled: (form) Enable or disable downloading for this video (optional)
     - parameter originallyPublishedAt: (form) Date when the content was originally published (optional)
     - parameter scheduleUpdate: (form)  (optional)
     - parameter thumbnailfile: (form) Video thumbnail file (optional)
     - parameter previewfile: (form) Video preview file (optional)
     - parameter videoPasswords: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<VideoUploadResponse> 
     */
    open class func importVideoWithRequestBuilder(name: String, channelId: Int, targetUrl: String? = nil, magnetUri: String? = nil, torrentfile: URL? = nil, privacy: VideoPrivacySet? = nil, category: Int? = nil, licence: Int? = nil, language: String? = nil, description: String? = nil, waitTranscoding: Bool? = nil, generateTranscription: Bool? = nil, support: String? = nil, nsfw: Bool? = nil, nsfwSummary: JSONValue? = nil, nsfwFlags: NSFWFlag? = nil, tags: Set<String>? = nil, commentsPolicy: VideoCommentsPolicySet? = nil, downloadEnabled: Bool? = nil, originallyPublishedAt: Date? = nil, scheduleUpdate: VideoScheduledUpdate? = nil, thumbnailfile: URL? = nil, previewfile: URL? = nil, videoPasswords: Set<String>? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<VideoUploadResponse> {
        let localVariablePath = "/api/v1/videos/imports"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "targetUrl": targetUrl?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "magnetUri": magnetUri?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "torrentfile": torrentfile?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "name": name.asParameter(codableHelper: apiConfiguration.codableHelper),
            "channelId": channelId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "privacy": privacy?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "category": category?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "licence": licence?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "language": language?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "description": description?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "waitTranscoding": waitTranscoding?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "generateTranscription": generateTranscription?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "support": support?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "nsfw": nsfw?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "nsfwSummary": nsfwSummary?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "nsfwFlags": nsfwFlags?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "tags": tags?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "commentsPolicy": commentsPolicy?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "downloadEnabled": downloadEnabled?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "originallyPublishedAt": originallyPublishedAt?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "scheduleUpdate": scheduleUpdate?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "thumbnailfile": thumbnailfile?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "previewfile": previewfile?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "videoPasswords": videoPasswords?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VideoUploadResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
