//
// ActorImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ActorImage: Sendable, Codable, ParameterConvertible, Hashable {

    /** Deprecated in PeerTube v8.0, use fileUrl instead */
    @available(*, deprecated, message: "This property is deprecated.")
    public var path: String?
    /** **PeerTube >= 7.1** */
    public var fileUrl: String?
    public var width: Int?
    /** **PeerTube >= 7.3** */
    public var height: Int?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(path: String? = nil, fileUrl: String? = nil, width: Int? = nil, height: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.path = path
        self.fileUrl = fileUrl
        self.width = width
        self.height = height
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case fileUrl
        case width
        case height
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(fileUrl, forKey: .fileUrl)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

