//
// AddVideoPasswordRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddVideoPasswordRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var password: String?

    public init(password: String? = nil) {
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

