//
// ApiV1UsersMeNewFeatureInfoReadPostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiV1UsersMeNewFeatureInfoReadPostRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var feature: NewFeatureInfoType

    public init(feature: NewFeatureInfoType) {
        self.feature = feature
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case feature
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(feature, forKey: .feature)
    }
}

