//
// ChannelActivityListResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChannelActivityListResponseDataInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    public var account: AccountSummary?
    public var action: ChannelActivityListResponseDataInnerAction?
    public var targetType: ChannelActivityListResponseDataInnerTargetType?
    public var details: [String: JSONValue]?
    public var createdAt: Date?
    public var channel: ChannelActivityListResponseDataInnerChannel?
    public var video: ChannelActivityListResponseDataInnerVideo?
    public var videoImport: ChannelActivityListResponseDataInnerVideoImport?
    public var playlist: ChannelActivityListResponseDataInnerPlaylist?
    public var channelSync: ChannelActivityListResponseDataInnerChannelSync?

    public init(id: Int? = nil, account: AccountSummary? = nil, action: ChannelActivityListResponseDataInnerAction? = nil, targetType: ChannelActivityListResponseDataInnerTargetType? = nil, details: [String: JSONValue]? = nil, createdAt: Date? = nil, channel: ChannelActivityListResponseDataInnerChannel? = nil, video: ChannelActivityListResponseDataInnerVideo? = nil, videoImport: ChannelActivityListResponseDataInnerVideoImport? = nil, playlist: ChannelActivityListResponseDataInnerPlaylist? = nil, channelSync: ChannelActivityListResponseDataInnerChannelSync? = nil) {
        self.id = id
        self.account = account
        self.action = action
        self.targetType = targetType
        self.details = details
        self.createdAt = createdAt
        self.channel = channel
        self.video = video
        self.videoImport = videoImport
        self.playlist = playlist
        self.channelSync = channelSync
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case account
        case action
        case targetType
        case details
        case createdAt
        case channel
        case video
        case videoImport
        case playlist
        case channelSync
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(action, forKey: .action)
        try container.encodeIfPresent(targetType, forKey: .targetType)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(channel, forKey: .channel)
        try container.encodeIfPresent(video, forKey: .video)
        try container.encodeIfPresent(videoImport, forKey: .videoImport)
        try container.encodeIfPresent(playlist, forKey: .playlist)
        try container.encodeIfPresent(channelSync, forKey: .channelSync)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ChannelActivityListResponseDataInner: Identifiable {}
