//
// ChannelActivityListResponseDataInnerPlaylist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChannelActivityListResponseDataInnerPlaylist: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let uuidRule = StringRule(minLength: 36, maxLength: 36, pattern: "/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/")
    public var id: Int?
    public var name: String?
    public var uuid: UUID?
    /** translation of a uuid v4 with a bigger alphabet to have a shorter uuid */
    public var shortUUID: String?
    public var url: String?

    public init(id: Int? = nil, name: String? = nil, uuid: UUID? = nil, shortUUID: String? = nil, url: String? = nil) {
        self.id = id
        self.name = name
        self.uuid = uuid
        self.shortUUID = shortUUID
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case uuid
        case shortUUID
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(shortUUID, forKey: .shortUUID)
        try container.encodeIfPresent(url, forKey: .url)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ChannelActivityListResponseDataInnerPlaylist: Identifiable {}
