//
// ChannelActivityListResponseDataInnerChannelSync.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChannelActivityListResponseDataInnerChannelSync: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var externalChannelUrl: String?

    public init(id: Int? = nil, externalChannelUrl: String? = nil) {
        self.id = id
        self.externalChannelUrl = externalChannelUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case externalChannelUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(externalChannelUrl, forKey: .externalChannelUrl)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ChannelActivityListResponseDataInnerChannelSync: Identifiable {}
