//
// ChannelActivityListResponseDataInnerChannel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChannelActivityListResponseDataInnerChannel: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var name: String?
    public var displayName: String?
    public var url: String?

    public init(id: Int? = nil, name: String? = nil, displayName: String? = nil, url: String? = nil) {
        self.id = id
        self.name = name
        self.displayName = displayName
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case displayName
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(url, forKey: .url)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ChannelActivityListResponseDataInnerChannel: Identifiable {}
