//
// GetVideoPlaylistVideos200ResponseDataInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetVideoPlaylistVideos200ResponseDataInner: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** object id for the video */
    public var id: Int?
    public var position: Int?
    public var startTimestamp: Int?
    public var stopTimestamp: Int?
    public var video: Video?

    public init(id: Int? = nil, position: Int? = nil, startTimestamp: Int? = nil, stopTimestamp: Int? = nil, video: Video? = nil) {
        self.id = id
        self.position = position
        self.startTimestamp = startTimestamp
        self.stopTimestamp = stopTimestamp
        self.video = video
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case position
        case startTimestamp
        case stopTimestamp
        case video
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(startTimestamp, forKey: .startTimestamp)
        try container.encodeIfPresent(stopTimestamp, forKey: .stopTimestamp)
        try container.encodeIfPresent(video, forKey: .video)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetVideoPlaylistVideos200ResponseDataInner: Identifiable {}
