//
// InviteVideoChannelCollaborator200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InviteVideoChannelCollaborator200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var collaborator: VideoChannelCollaborator?

    public init(collaborator: VideoChannelCollaborator? = nil) {
        self.collaborator = collaborator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case collaborator
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(collaborator, forKey: .collaborator)
    }
}

