//
// InviteVideoChannelCollaboratorRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InviteVideoChannelCollaboratorRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** Local user username to invite */
    public var accountHandle: String?

    public init(accountHandle: String? = nil) {
        self.accountHandle = accountHandle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accountHandle
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(accountHandle, forKey: .accountHandle)
    }
}

