//
// ListVideoStoryboards200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ListVideoStoryboards200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var storyboards: [Storyboard]?

    public init(storyboards: [Storyboard]? = nil) {
        self.storyboards = storyboards
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case storyboards
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(storyboards, forKey: .storyboards)
    }
}

