//
// LiveVideoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiveVideoResponse: Sendable, Codable, ParameterConvertible, Hashable {

    /** Included in the response if an appropriate token is provided */
    public var rtmpUrl: String?
    /** Included in the response if an appropriate token is provided */
    public var rtmpsUrl: String?
    /** RTMP stream key to use to stream into this live video. Included in the response if an appropriate token is provided */
    public var streamKey: String?
    public var saveReplay: Bool?
    public var replaySettings: LiveVideoReplaySettings?
    /** User can stream multiple times in a permanent live */
    public var permanentLive: Bool?
    /** User can select live latency mode if enabled by the instance */
    public var latencyMode: LiveVideoLatencyMode?
    public var schedules: [LiveSchedule]?

    public init(rtmpUrl: String? = nil, rtmpsUrl: String? = nil, streamKey: String? = nil, saveReplay: Bool? = nil, replaySettings: LiveVideoReplaySettings? = nil, permanentLive: Bool? = nil, latencyMode: LiveVideoLatencyMode? = nil, schedules: [LiveSchedule]? = nil) {
        self.rtmpUrl = rtmpUrl
        self.rtmpsUrl = rtmpsUrl
        self.streamKey = streamKey
        self.saveReplay = saveReplay
        self.replaySettings = replaySettings
        self.permanentLive = permanentLive
        self.latencyMode = latencyMode
        self.schedules = schedules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rtmpUrl
        case rtmpsUrl
        case streamKey
        case saveReplay
        case replaySettings
        case permanentLive
        case latencyMode
        case schedules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(rtmpUrl, forKey: .rtmpUrl)
        try container.encodeIfPresent(rtmpsUrl, forKey: .rtmpsUrl)
        try container.encodeIfPresent(streamKey, forKey: .streamKey)
        try container.encodeIfPresent(saveReplay, forKey: .saveReplay)
        try container.encodeIfPresent(replaySettings, forKey: .replaySettings)
        try container.encodeIfPresent(permanentLive, forKey: .permanentLive)
        try container.encodeIfPresent(latencyMode, forKey: .latencyMode)
        try container.encodeIfPresent(schedules, forKey: .schedules)
    }
}

