//
// NewFeatureInfoType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Represent a new feature that can be displayed to inform users. One of the following values:    - &#x60;1&#x60; CHANNEL_COLLABORATION  */
public enum NewFeatureInfoType: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
}
