//
// NSFWFlag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/**  NSFW flags (can be combined using bitwise or operator) - &#x60;0&#x60; NONE - &#x60;1&#x60; VIOLENT - &#x60;2&#x60; EXPLICIT_SEX  */
public enum NSFWFlag: Int, Sendable, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
    case _4 = 4
}
