//
// PlayerChannelSettingsUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Player settings update for a channel */
public struct PlayerChannelSettingsUpdate: Sendable, Codable, ParameterConvertible, Hashable {

    public var theme: PlayerThemeChannelSetting

    public init(theme: PlayerThemeChannelSetting) {
        self.theme = theme
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case theme
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(theme, forKey: .theme)
    }
}

