//
// PlayerChannelSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Player settings for a channel */
public struct PlayerChannelSettings: Sendable, Codable, ParameterConvertible, Hashable {

    public var theme: PlayerThemeChannelSetting?

    public init(theme: PlayerThemeChannelSetting? = nil) {
        self.theme = theme
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case theme
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(theme, forKey: .theme)
    }
}

