//
// PlayerTheme.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The player theme to use */
public enum PlayerTheme: String, Sendable, Codable, CaseIterable {
    case galaxy = "galaxy"
    case lucide = "lucide"
}
