//
// PlayerThemeChannelSetting.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Player theme setting for a channel:   - &#x60;instance-default&#x60; Use the instance default theme   - &#x60;galaxy&#x60; Use the galaxy theme   - &#x60;lucide&#x60; Use the lucide theme  */
public enum PlayerThemeChannelSetting: String, Sendable, Codable, CaseIterable {
    case instanceDefault = "instance-default"
    case galaxy = "galaxy"
    case lucide = "lucide"
}
