//
// ServerConfigCustomDefaults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomDefaults: Sendable, Codable, ParameterConvertible, Hashable {

    public var publish: ServerConfigCustomDefaultsPublish?
    public var p2p: ServerConfigCustomDefaultsP2p?
    public var player: ServerConfigCustomDefaultsPlayer?

    public init(publish: ServerConfigCustomDefaultsPublish? = nil, p2p: ServerConfigCustomDefaultsP2p? = nil, player: ServerConfigCustomDefaultsPlayer? = nil) {
        self.publish = publish
        self.p2p = p2p
        self.player = player
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publish
        case p2p
        case player
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(publish, forKey: .publish)
        try container.encodeIfPresent(p2p, forKey: .p2p)
        try container.encodeIfPresent(player, forKey: .player)
    }
}

