//
// ServerConfigCustomDefaultsPublish.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomDefaultsPublish: Sendable, Codable, ParameterConvertible, Hashable {

    public var downloadEnabled: Bool?
    public var commentsPolicy: VideoCommentsPolicySet?
    public var privacy: VideoPrivacySet?
    /** licence id of the video (see [/videos/licences](#operation/getLicences)) */
    public var licence: Int?

    public init(downloadEnabled: Bool? = nil, commentsPolicy: VideoCommentsPolicySet? = nil, privacy: VideoPrivacySet? = nil, licence: Int? = nil) {
        self.downloadEnabled = downloadEnabled
        self.commentsPolicy = commentsPolicy
        self.privacy = privacy
        self.licence = licence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case downloadEnabled
        case commentsPolicy
        case privacy
        case licence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(downloadEnabled, forKey: .downloadEnabled)
        try container.encodeIfPresent(commentsPolicy, forKey: .commentsPolicy)
        try container.encodeIfPresent(privacy, forKey: .privacy)
        try container.encodeIfPresent(licence, forKey: .licence)
    }
}

