//
// ServerError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerError: Sendable, Codable, ParameterConvertible, Hashable {

    public var type: String?
    public var detail: String?
    public var status: Int?
    public var code: String?

    public init(type: String? = nil, detail: String? = nil, status: Int? = nil, code: String? = nil) {
        self.type = type
        self.detail = detail
        self.status = status
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case detail
        case status
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(detail, forKey: .detail)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(code, forKey: .code)
    }
}

