//
// ServerConfigCustomDefaultsPlayer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomDefaultsPlayer: Sendable, Codable, ParameterConvertible, Hashable {

    public var autoPlay: Bool?

    public init(autoPlay: Bool? = nil) {
        self.autoPlay = autoPlay
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case autoPlay
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(autoPlay, forKey: .autoPlay)
    }
}

