//
// ServerConfigCustomDefaultsP2p.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServerConfigCustomDefaultsP2p: Sendable, Codable, ParameterConvertible, Hashable {

    public var webapp: ServerConfigEmail?
    public var embed: ServerConfigEmail?

    public init(webapp: ServerConfigEmail? = nil, embed: ServerConfigEmail? = nil) {
        self.webapp = webapp
        self.embed = embed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webapp
        case embed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(webapp, forKey: .webapp)
        try container.encodeIfPresent(embed, forKey: .embed)
    }
}

