//
// Storyboard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Storyboard: Sendable, Codable, ParameterConvertible, Hashable {

    /** Deprecated in PeerTube v8.0, use fileUrl instead */
    @available(*, deprecated, message: "This property is deprecated.")
    public var storyboardPath: String?
    /** **PeerTube >= 7.1** */
    public var fileUrl: String?
    public var totalHeight: Int?
    public var totalWidth: Int?
    public var spriteHeight: Int?
    public var spriteWidth: Int?
    public var spriteDuration: Int?

    public init(storyboardPath: String? = nil, fileUrl: String? = nil, totalHeight: Int? = nil, totalWidth: Int? = nil, spriteHeight: Int? = nil, spriteWidth: Int? = nil, spriteDuration: Int? = nil) {
        self.storyboardPath = storyboardPath
        self.fileUrl = fileUrl
        self.totalHeight = totalHeight
        self.totalWidth = totalWidth
        self.spriteHeight = spriteHeight
        self.spriteWidth = spriteWidth
        self.spriteDuration = spriteDuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case storyboardPath
        case fileUrl
        case totalHeight
        case totalWidth
        case spriteHeight
        case spriteWidth
        case spriteDuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(storyboardPath, forKey: .storyboardPath)
        try container.encodeIfPresent(fileUrl, forKey: .fileUrl)
        try container.encodeIfPresent(totalHeight, forKey: .totalHeight)
        try container.encodeIfPresent(totalWidth, forKey: .totalWidth)
        try container.encodeIfPresent(spriteHeight, forKey: .spriteHeight)
        try container.encodeIfPresent(spriteWidth, forKey: .spriteWidth)
        try container.encodeIfPresent(spriteDuration, forKey: .spriteDuration)
    }
}

