//
// TokenSession.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TokenSession: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: Int?
    /** Is this session the current one? */
    public var currentSession: Bool?
    /** Device used to login */
    public var loginDevice: String?
    /** IP address used to login */
    public var loginIP: String?
    /** Date of the login */
    public var loginDate: Date?
    public var lastActivityDevice: String?
    public var lastActivityIP: String?
    public var lastActivityDate: Date?
    public var createdAt: Date?

    public init(id: Int? = nil, currentSession: Bool? = nil, loginDevice: String? = nil, loginIP: String? = nil, loginDate: Date? = nil, lastActivityDevice: String? = nil, lastActivityIP: String? = nil, lastActivityDate: Date? = nil, createdAt: Date? = nil) {
        self.id = id
        self.currentSession = currentSession
        self.loginDevice = loginDevice
        self.loginIP = loginIP
        self.loginDate = loginDate
        self.lastActivityDevice = lastActivityDevice
        self.lastActivityIP = lastActivityIP
        self.lastActivityDate = lastActivityDate
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case currentSession
        case loginDevice
        case loginIP
        case loginDate
        case lastActivityDevice
        case lastActivityIP
        case lastActivityDate
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(currentSession, forKey: .currentSession)
        try container.encodeIfPresent(loginDevice, forKey: .loginDevice)
        try container.encodeIfPresent(loginIP, forKey: .loginIP)
        try container.encodeIfPresent(loginDate, forKey: .loginDate)
        try container.encodeIfPresent(lastActivityDevice, forKey: .lastActivityDevice)
        try container.encodeIfPresent(lastActivityIP, forKey: .lastActivityIP)
        try container.encodeIfPresent(lastActivityDate, forKey: .lastActivityDate)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TokenSession: Identifiable {}
