//
// UpdateClientLanguageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateClientLanguageRequest: Sendable, Codable, ParameterConvertible, Hashable {

    /** Language code to set */
    public var language: String

    public init(language: String) {
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(language, forKey: .language)
    }
}

