//
// UserWithStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserWithStats: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let usernameRule = StringRule(minLength: 1, maxLength: 50, pattern: "/^[a-z0-9._]+$/")
    public var id: Int?
    /** immutable name of the user, used to find or mention its actor */
    public var username: String?
    /** The user email */
    public var email: String?
    /** Has the user confirmed their email address? */
    public var emailVerified: Bool?
    /** Has the user accepted to display the email publicly? */
    public var emailPublic: Bool?
    public var nsfwPolicy: NSFWPolicy?
    public var nsfwFlagsDisplayed: NSFWFlag?
    public var nsfwFlagsHidden: NSFWFlag?
    public var nsfwFlagsWarned: NSFWFlag?
    public var nsfwFlagsBlurred: NSFWFlag?
    public var adminFlags: UserAdminFlags?
    /** Automatically start playing the upcoming video after the currently playing video */
    public var autoPlayNextVideo: Bool?
    /** Automatically start playing the video on the playlist after the currently playing video */
    public var autoPlayNextVideoPlaylist: Bool?
    /** Automatically start playing the video on the watch page */
    public var autoPlayVideo: Bool?
    /** whether to enable P2P in the player or not */
    public var p2pEnabled: Bool?
    /** whether to keep track of watched history or not */
    public var videosHistoryEnabled: Bool?
    /** list of languages to filter videos down to */
    public var videoLanguages: [String]?
    /** default language for this user */
    public var language: String?
    /** The user video quota in bytes */
    public var videoQuota: Int?
    /** The user daily video quota in bytes */
    public var videoQuotaDaily: Int?
    public var role: UserRole?
    /** Theme enabled by this user */
    public var theme: String?
    public var account: Account?
    public var notificationSettings: UserNotificationSettings?
    public var videoChannels: [VideoChannel]?
    public var blocked: Bool?
    public var blockedReason: String?
    public var noInstanceConfigWarningModal: Bool?
    public var noAccountSetupWarningModal: Bool?
    public var noWelcomeModal: Bool?
    public var createdAt: String?
    /** Auth plugin to use to authenticate the user */
    public var pluginAuth: String?
    public var lastLoginDate: Date?
    /** Whether the user has enabled two-factor authentication or not */
    public var twoFactorEnabled: Bool?
    /** New features information the user has read */
    public var newFeaturesInfoRead: Double?
    /** Count of videos published */
    public var videosCount: Int?
    /** Count of reports/abuses of which the user is a target */
    public var abusesCount: Int?
    /** Count of reports/abuses created by the user and accepted/acted upon by the moderation team */
    public var abusesAcceptedCount: Int?
    /** Count of reports/abuses created by the user */
    public var abusesCreatedCount: Int?
    /** Count of comments published */
    public var videoCommentsCount: Int?

    public init(id: Int? = nil, username: String? = nil, email: String? = nil, emailVerified: Bool? = nil, emailPublic: Bool? = nil, nsfwPolicy: NSFWPolicy? = nil, nsfwFlagsDisplayed: NSFWFlag? = nil, nsfwFlagsHidden: NSFWFlag? = nil, nsfwFlagsWarned: NSFWFlag? = nil, nsfwFlagsBlurred: NSFWFlag? = nil, adminFlags: UserAdminFlags? = nil, autoPlayNextVideo: Bool? = nil, autoPlayNextVideoPlaylist: Bool? = nil, autoPlayVideo: Bool? = nil, p2pEnabled: Bool? = nil, videosHistoryEnabled: Bool? = nil, videoLanguages: [String]? = nil, language: String? = nil, videoQuota: Int? = nil, videoQuotaDaily: Int? = nil, role: UserRole? = nil, theme: String? = nil, account: Account? = nil, notificationSettings: UserNotificationSettings? = nil, videoChannels: [VideoChannel]? = nil, blocked: Bool? = nil, blockedReason: String? = nil, noInstanceConfigWarningModal: Bool? = nil, noAccountSetupWarningModal: Bool? = nil, noWelcomeModal: Bool? = nil, createdAt: String? = nil, pluginAuth: String? = nil, lastLoginDate: Date? = nil, twoFactorEnabled: Bool? = nil, newFeaturesInfoRead: Double? = nil, videosCount: Int? = nil, abusesCount: Int? = nil, abusesAcceptedCount: Int? = nil, abusesCreatedCount: Int? = nil, videoCommentsCount: Int? = nil) {
        self.id = id
        self.username = username
        self.email = email
        self.emailVerified = emailVerified
        self.emailPublic = emailPublic
        self.nsfwPolicy = nsfwPolicy
        self.nsfwFlagsDisplayed = nsfwFlagsDisplayed
        self.nsfwFlagsHidden = nsfwFlagsHidden
        self.nsfwFlagsWarned = nsfwFlagsWarned
        self.nsfwFlagsBlurred = nsfwFlagsBlurred
        self.adminFlags = adminFlags
        self.autoPlayNextVideo = autoPlayNextVideo
        self.autoPlayNextVideoPlaylist = autoPlayNextVideoPlaylist
        self.autoPlayVideo = autoPlayVideo
        self.p2pEnabled = p2pEnabled
        self.videosHistoryEnabled = videosHistoryEnabled
        self.videoLanguages = videoLanguages
        self.language = language
        self.videoQuota = videoQuota
        self.videoQuotaDaily = videoQuotaDaily
        self.role = role
        self.theme = theme
        self.account = account
        self.notificationSettings = notificationSettings
        self.videoChannels = videoChannels
        self.blocked = blocked
        self.blockedReason = blockedReason
        self.noInstanceConfigWarningModal = noInstanceConfigWarningModal
        self.noAccountSetupWarningModal = noAccountSetupWarningModal
        self.noWelcomeModal = noWelcomeModal
        self.createdAt = createdAt
        self.pluginAuth = pluginAuth
        self.lastLoginDate = lastLoginDate
        self.twoFactorEnabled = twoFactorEnabled
        self.newFeaturesInfoRead = newFeaturesInfoRead
        self.videosCount = videosCount
        self.abusesCount = abusesCount
        self.abusesAcceptedCount = abusesAcceptedCount
        self.abusesCreatedCount = abusesCreatedCount
        self.videoCommentsCount = videoCommentsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case email
        case emailVerified
        case emailPublic
        case nsfwPolicy
        case nsfwFlagsDisplayed
        case nsfwFlagsHidden
        case nsfwFlagsWarned
        case nsfwFlagsBlurred
        case adminFlags
        case autoPlayNextVideo
        case autoPlayNextVideoPlaylist
        case autoPlayVideo
        case p2pEnabled
        case videosHistoryEnabled
        case videoLanguages
        case language
        case videoQuota
        case videoQuotaDaily
        case role
        case theme
        case account
        case notificationSettings
        case videoChannels
        case blocked
        case blockedReason
        case noInstanceConfigWarningModal
        case noAccountSetupWarningModal
        case noWelcomeModal
        case createdAt
        case pluginAuth
        case lastLoginDate
        case twoFactorEnabled
        case newFeaturesInfoRead
        case videosCount
        case abusesCount
        case abusesAcceptedCount
        case abusesCreatedCount
        case videoCommentsCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(emailVerified, forKey: .emailVerified)
        try container.encodeIfPresent(emailPublic, forKey: .emailPublic)
        try container.encodeIfPresent(nsfwPolicy, forKey: .nsfwPolicy)
        try container.encodeIfPresent(nsfwFlagsDisplayed, forKey: .nsfwFlagsDisplayed)
        try container.encodeIfPresent(nsfwFlagsHidden, forKey: .nsfwFlagsHidden)
        try container.encodeIfPresent(nsfwFlagsWarned, forKey: .nsfwFlagsWarned)
        try container.encodeIfPresent(nsfwFlagsBlurred, forKey: .nsfwFlagsBlurred)
        try container.encodeIfPresent(adminFlags, forKey: .adminFlags)
        try container.encodeIfPresent(autoPlayNextVideo, forKey: .autoPlayNextVideo)
        try container.encodeIfPresent(autoPlayNextVideoPlaylist, forKey: .autoPlayNextVideoPlaylist)
        try container.encodeIfPresent(autoPlayVideo, forKey: .autoPlayVideo)
        try container.encodeIfPresent(p2pEnabled, forKey: .p2pEnabled)
        try container.encodeIfPresent(videosHistoryEnabled, forKey: .videosHistoryEnabled)
        try container.encodeIfPresent(videoLanguages, forKey: .videoLanguages)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(videoQuota, forKey: .videoQuota)
        try container.encodeIfPresent(videoQuotaDaily, forKey: .videoQuotaDaily)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(theme, forKey: .theme)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(notificationSettings, forKey: .notificationSettings)
        try container.encodeIfPresent(videoChannels, forKey: .videoChannels)
        try container.encodeIfPresent(blocked, forKey: .blocked)
        try container.encodeIfPresent(blockedReason, forKey: .blockedReason)
        try container.encodeIfPresent(noInstanceConfigWarningModal, forKey: .noInstanceConfigWarningModal)
        try container.encodeIfPresent(noAccountSetupWarningModal, forKey: .noAccountSetupWarningModal)
        try container.encodeIfPresent(noWelcomeModal, forKey: .noWelcomeModal)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(pluginAuth, forKey: .pluginAuth)
        try container.encodeIfPresent(lastLoginDate, forKey: .lastLoginDate)
        try container.encodeIfPresent(twoFactorEnabled, forKey: .twoFactorEnabled)
        try container.encodeIfPresent(newFeaturesInfoRead, forKey: .newFeaturesInfoRead)
        try container.encodeIfPresent(videosCount, forKey: .videosCount)
        try container.encodeIfPresent(abusesCount, forKey: .abusesCount)
        try container.encodeIfPresent(abusesAcceptedCount, forKey: .abusesAcceptedCount)
        try container.encodeIfPresent(abusesCreatedCount, forKey: .abusesCreatedCount)
        try container.encodeIfPresent(videoCommentsCount, forKey: .videoCommentsCount)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserWithStats: Identifiable {}
