//
// VideoChannelActivityTarget.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The activity target:   - VIDEO: 1,   - PLAYLIST: 2,   - CHANNEL: 3,   - CHANNEL_SYNC: 4,   - VIDEO_IMPORT: 5  */
public enum VideoChannelActivityTarget: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
}
