//
// VideoChannelActivityAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The activity action:   - CREATE: 1   - UPDATE: 2   - DELETE: 3   - UPDATE_CAPTIONS: 4   - UPDATE_CHAPTERS: 5   - UPDATE_PASSWORDS: 6   - CREATE_STUDIO_TASKS: 7   - UPDATE_SOURCE_FILE: 8   - UPDATE_ELEMENTS: 9   - REMOVE_CHANNEL_OWNERSHIP: 10   - CREATE_CHANNEL_OWNERSHIP: 11  */
public enum VideoChannelActivityAction: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
    case _4 = 4
    case _5 = 5
    case _6 = 6
    case _7 = 7
    case _8 = 8
    case _9 = 9
    case _10 = 10
    case _11 = 11
}
