//
// VideoCaption.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoCaption: Sendable, Codable, ParameterConvertible, Hashable {

    public var language: VideoConstantStringLanguage?
    public var automaticallyGenerated: Bool?
    /** Deprecated in PeerTube v8.0, use fileUrl instead */
    @available(*, deprecated, message: "This property is deprecated.")
    public var captionPath: String?
    /** **PeerTube >= 7.1** */
    public var fileUrl: String?
    public var m3u8Url: String?
    public var updatedAt: Date?

    public init(language: VideoConstantStringLanguage? = nil, automaticallyGenerated: Bool? = nil, captionPath: String? = nil, fileUrl: String? = nil, m3u8Url: String? = nil, updatedAt: Date? = nil) {
        self.language = language
        self.automaticallyGenerated = automaticallyGenerated
        self.captionPath = captionPath
        self.fileUrl = fileUrl
        self.m3u8Url = m3u8Url
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case language
        case automaticallyGenerated
        case captionPath
        case fileUrl
        case m3u8Url
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(automaticallyGenerated, forKey: .automaticallyGenerated)
        try container.encodeIfPresent(captionPath, forKey: .captionPath)
        try container.encodeIfPresent(fileUrl, forKey: .fileUrl)
        try container.encodeIfPresent(m3u8Url, forKey: .m3u8Url)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

