//
// VideoStatsUserAgentDevicesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoStatsUserAgentDevicesInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: VideoStatsUserAgentDevice?
    public var viewers: Double?

    public init(name: VideoStatsUserAgentDevice? = nil, viewers: Double? = nil) {
        self.name = name
        self.viewers = viewers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case viewers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(viewers, forKey: .viewers)
    }
}

