//
// VideoStatsUserAgent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoStatsUserAgent: Sendable, Codable, ParameterConvertible, Hashable {

    public var clients: [VideoStatsOverallSubdivisionsInner]?
    public var devices: [VideoStatsUserAgentDevicesInner]?
    public var operatingSystem: [VideoStatsOverallSubdivisionsInner]?

    public init(clients: [VideoStatsOverallSubdivisionsInner]? = nil, devices: [VideoStatsUserAgentDevicesInner]? = nil, operatingSystem: [VideoStatsOverallSubdivisionsInner]? = nil) {
        self.clients = clients
        self.devices = devices
        self.operatingSystem = operatingSystem
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clients
        case devices
        case operatingSystem
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clients, forKey: .clients)
        try container.encodeIfPresent(devices, forKey: .devices)
        try container.encodeIfPresent(operatingSystem, forKey: .operatingSystem)
    }
}

