//
// VideoChannelCollaborator.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Representation of a channel collaboration */
public struct VideoChannelCollaborator: Sendable, Codable, ParameterConvertible, Hashable {

    public static let idRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var account: AccountSummary?
    public var state: VideoChannelCollaboratorState?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: Int? = nil, account: AccountSummary? = nil, state: VideoChannelCollaboratorState? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.account = account
        self.state = state
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case account
        case state
        case createdAt
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(state, forKey: .state)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension VideoChannelCollaborator: Identifiable {}
