//
// VideoStatsUserAgentDevice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum VideoStatsUserAgentDevice: String, Sendable, Codable, CaseIterable {
    case console = "console"
    case embedded = "embedded"
    case mobile = "mobile"
    case smarttv = "smarttv"
    case tablet = "tablet"
    case wearable = "wearable"
    case xr = "xr"
    case desktop = "desktop"
}
