//
// VideoStatsOverall.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VideoStatsOverall: Sendable, Codable, ParameterConvertible, Hashable {

    public var averageWatchTime: Double?
    public var totalWatchTime: Double?
    public var viewersPeak: Double?
    public var totalViewers: Double?
    public var viewersPeakDate: Date?
    public var countries: [VideoStatsOverallCountriesInner]?
    public var subdivisions: [VideoStatsOverallSubdivisionsInner]?

    public init(averageWatchTime: Double? = nil, totalWatchTime: Double? = nil, viewersPeak: Double? = nil, totalViewers: Double? = nil, viewersPeakDate: Date? = nil, countries: [VideoStatsOverallCountriesInner]? = nil, subdivisions: [VideoStatsOverallSubdivisionsInner]? = nil) {
        self.averageWatchTime = averageWatchTime
        self.totalWatchTime = totalWatchTime
        self.viewersPeak = viewersPeak
        self.totalViewers = totalViewers
        self.viewersPeakDate = viewersPeakDate
        self.countries = countries
        self.subdivisions = subdivisions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case averageWatchTime
        case totalWatchTime
        case viewersPeak
        case totalViewers
        case viewersPeakDate
        case countries
        case subdivisions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(averageWatchTime, forKey: .averageWatchTime)
        try container.encodeIfPresent(totalWatchTime, forKey: .totalWatchTime)
        try container.encodeIfPresent(viewersPeak, forKey: .viewersPeak)
        try container.encodeIfPresent(totalViewers, forKey: .totalViewers)
        try container.encodeIfPresent(viewersPeakDate, forKey: .viewersPeakDate)
        try container.encodeIfPresent(countries, forKey: .countries)
        try container.encodeIfPresent(subdivisions, forKey: .subdivisions)
    }
}

